Initial nextjs api endpoint commit
CivicActions/pgov-cms pull request #46
Opened 2024-12-19 21:07 UTC by dgading

2025-01-15 16:21 UTC, dgading commented
Linking the NextJS tutorial page which probably explains it better than I did https://nextjs.org/learn-pages-router/basics/api-routes

2025-01-16 17:55 UTC, openprivacy commented
@dgading thanks for the link - quite a rabbit hole that I never got to the bottom of. It seems NextJS is being secure here, but as with writing any APIs, whoever reviews your code should keep the OWASP API Top 10 in mind.
https://owasp.org/API-Security/editions/2023/en/0x11-t10/

2025-02-04 07:27 UTC, acabouet commented on src/frontend/lib/graphqlQueries.ts
> +             fieldId
this field is gone now on goals and breaks the build when in the query

2025-02-04 07:30 UTC, acabouet commented on src/frontend/components/view--goal-search.tsx
> +      console.log(data)
probs need the console.logs out of here if we're gonna deploy this

2025-02-04 07:32 UTC, acabouet commented on src/frontend/components/view--goal-search.tsx
> +    const url = `/api/goal-search?fulltext=${fulltext}`;
do we need to sanitize this input at all? this is pulling from the text field users type into rather than the tag cloud right?

2025-02-04 07:32 UTC, acabouet requested changes
Did the OWASP API security top 10 review and made some comments.

2025-02-04 14:52 UTC, dgading commented on src/frontend/lib/graphqlQueries.ts
> +             fieldId
Just found this one in my PR of the updated designs. Should be good once I rebase this for the new layout.

2025-02-04 20:21 UTC, dgading commented on src/frontend/components/view--goal-search.tsx
> +      console.log(data)
These should all be removed, except in the return of an error and in the current search header, which I think will be deleted soon.

2025-02-04 20:24 UTC, dgading commented on src/frontend/components/view--goal-search.tsx
> +    const url = `/api/goal-search?fulltext=${fulltext}`;
I think we are fine without sanitizing it. Drupal is ultimately getting the response and will be running its own sanitization on the string. Usually I am more worried about sanitizing the output on the pages, which we might want to add. We don't sanitize anything going into DKAN from the React code, but let the processors in PHP handle it and log anything weird.

2025-02-04 20:28 UTC, dgading commented
New testing instructions:

1. Run ddev drush cim to get new search api config
2. Re index search api to get new tokenizer and case insensitivity features
3. Build frontend
4. You should now be able to search fulltext (the new design doesn't have a search button so I have it filtering while you type)
5. It should do partial matches now
6. You can also filter by topics

2025-02-05 01:16 UTC, acabouet approved these changes

2025-02-05 01:16 UTC, merged